version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - node_modules:/node_modules
    tty: true
    stdin_open: true
    environment:
    - NUXT_ENV_APP_ENV=development
    - NUXT_ENV_WHIM_ENV=staging
    command: ash -c "yarn && yarn dev"

volumes:
  node_modules:
    driver: local